/*
Provides a gRPC server that defines an interface for modifying the behavior of the simulation while it
is running. The code in this package references Go code that is generated by the protobuf compiler.
The protobuf compiler generates Go code as part of the build. The code in this package then calls
the generated code. See the 'nbodygrpc' package for more info on the generated code, and also the
.proto file.
*/
package grpcserver
