apiVersion: 1

#
# A Grafana data source that finds the Prometheus instance running in Docker that was
# started by the scripts/start-containers script. You can get the data source out of
# Grafana this way:
#
#  curl -u root:secret http://localhost:3000/api/datasources/1 | python -m json.tool
#
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    password: ""
    user: ""
    database: ""
    basicAuth: false
    basicAuthUser: ""
    basicAuthPassword: ""
    withCredentials: false
    isDefault: true
    jsonData:
      "httpMethod": "GET"
      "keepCookies": []
    secureJsonData: {}
    version: 1
    editable: true
